services:
  list-n-run-server:
    build:
      context: .
      target: build_dev
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - postgres-development
    volumes:
      - .:/app
      - /app/node_modules
  postgres-development:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
volumes:
  postgres-data:
  node_modules:
