# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.2.2
FROM ruby:$RUBY_VERSION AS build_dev

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips \
      postgresql-client netcat-openbsd

RUN curl -fsSL https://deb.nodesource.com/setup_18.x
RUN apt-get install -y nodejs

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y yarn
RUN rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Verify Node.js and Yarn installation
RUN node -v && yarn -v

RUN gem install overmind

COPY package-lock.json .
COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install

COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
EXPOSE 3035

CMD ["overmind", "start", "-f", "Procfile.dev"]